### ISSUE TITLE
Just Citing/Acknowledging Your Work

### ISSUE THREAD

**Issue by anonhostpi** [owlks4/DBPF-package-manager#5]
Gonna open then immediately close this issue. Just reaching out to let you know that my DBPF wiki cites this repository.
- wiki: https://anonhostpi.github.io/DBPF.js/docs/other/spec/

I'm avidly working on my own DBPF reader. If you see anything missing from my wiki (...or my lib), feel free let me know! I'm avidly working on them every day

I just wanted to be sure you knew I was citing your work! Very interesting tool by the way. Is this going to be an alternative to S4PE?

**Comment by owlks4** [comment]
Thanks for letting me know - good to know that others are still interested in old Maxis formats :P 

This exists because I was a bit surprised at the lack of flexibility in S3PE (and possibly S4PE)'s package parser. My impression is that they were written for a manipulating only their very specific kind of DBPF package - a task they do really well, but without much room for generalising to the many other DBPF versions and variations. That's why this project immediately deals with the major/minor/index versions and has (e.g.) lots of functions passed as arguments in the Type ID manager - it's to make it easier to extend. If I ever get back to it, that is!

**Comment by anonhostpi** [comment]
Same! Mine is written in TS tho. Can use it in the browser:

https://anonhostpi.github.io/DBPF.js/playground

Still a work in Progress. Right now it only handles THUMs, but I'm currently working on adding the rest. It has a plugin system too.

Supposedly, mine also works with v1.0/1.1 (Sims 2, TSO, SC4, etc). You can port some of my code, if you want
